### ISSUE TITLE
Add link to CAMS > UWL Semantic Web Resources page

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#1]
@gerontakos 

❓ Add link to [Newspaper Genre List](https://doi.org/10.6069/uwlib.55.d.5) HTML+RDFa from the [University of Washington Libraries Semantic Web Resources](https://www.lib.washington.edu/cams/swr) page > LOCAL VOCABULARIES heading❔ 

(I'm happy to edit the page and add the link; just wanted to check and see whether/when you are ready to "go public.")

**Comment by gerontakos** [comment]
I added it
