### ISSUE TITLE
update file names, file name references, and DOI configuration for linked data platforms

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#12]
AND:
- Publish RDF serializations in a uwlib-cams repo, following [naming conventions](https://github.com/uwlib-cams/uwlswd/wiki/naming-conventions)
- Update [DOI worksheet 2.0](https://docs.google.com/spreadsheets/d/1XKesA8lvCLGjCkw6jQ7Avoq25TbWOHnXuD29VuwRKZE/edit?usp=sharing)\*

\**Restricted access*

See steps taken for Newspaper Genre List at https://github.com/uwlib-cams/uwlswd_vocabs/issues/8#issuecomment-1426246993

**Comment by briesenberg07** [comment]
Ready for @briesenberg07 to update DOI URL

**Comment by briesenberg07** [comment]
Hi @cspayne / Preparing to update DOI, noticed that `dct:hasFormat` triples don't currently include the HTML + RDFa serialization, if not the current file. This format should also be included where applicable in the `dct:hasFormat` triples, per the [discussion on `dct:hasFormat`](https://github.com/uwlib-cams/uwlswd/discussions/14).
Please add these, then I'll do my to-dos above. Thank you!

**Comment by cspayne** [comment]
@briesenberg07
Thank you for catching that! I've added it to the serialization script and updated the linked data platforms files.
