### ISSUE TITLE
update file names, file name references, and DOI configuration for LD vocabs: childrens' lit categories

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#13]
AND:
- Publish RDF serializations in a uwlib-cams repo, following [naming conventions](https://github.com/uwlib-cams/uwlswd/wiki/naming-conventions)
- Update [DOI worksheet 2.0](https://docs.google.com/spreadsheets/d/1XKesA8lvCLGjCkw6jQ7Avoq25TbWOHnXuD29VuwRKZE/edit?usp=sharing)\*

\**Restricted access*

See steps taken for Newspaper Genre List at https://github.com/uwlib-cams/uwlswd_vocabs/issues/8#issuecomment-1426246993

**Comment by briesenberg07** [comment]
This is ready to have @briesenberg07 update DOI URL

**Comment by cspayne** [comment]
@briesenberg07 
This one is all set too!

**Comment by briesenberg07** [comment]
@briesenberg07 to-dos:

- [x] Update URL for DOI
- [x] Confirm DOI dereferences to new URL
- [] Delete files from old storage location
