### ISSUE TITLE
update file names, file name references, and DOI configuration for UWL RDA extension

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#15]
AND:
- Publish RDF serializations in a uwlib-cams repo, following [naming conventions](https://github.com/uwlib-cams/uwlswd/wiki/naming-conventions)
- Update [DOI worksheet 2.0](https://docs.google.com/spreadsheets/d/1XKesA8lvCLGjCkw6jQ7Avoq25TbWOHnXuD29VuwRKZE/edit?usp=sharing)\*

\**Restricted access*

See steps taken for Newspaper Genre List at https://github.com/uwlib-cams/uwlswd_vocabs/issues/8#issuecomment-1426246993

**Comment by briesenberg07** [comment]
Note that changing file locations/URLs for this vocab will affect sinopia_maps code. *See https://github.com/uwlib-cams/map_storage/issues/49#issuecomment-1635043160.*

**Comment by cspayne** [comment]
map_storage has also been updated.

**Comment by briesenberg07** [comment]
I had not thought of that!!! Thank you for catching that @cspayne
