### ISSUE TITLE
update file names, file name references, and DOI configuration for classes

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#17]
AND:
- Publish RDF serializations in a uwlib-cams repo, following [naming conventions](https://github.com/uwlib-cams/uwlswd/wiki/naming-conventions)
- Update [DOI worksheet 2.0](https://docs.google.com/spreadsheets/d/1XKesA8lvCLGjCkw6jQ7Avoq25TbWOHnXuD29VuwRKZE/edit?usp=sharing)\*

\**Restricted access*

See steps taken for Newspaper Genre List at https://github.com/uwlib-cams/uwlswd_vocabs/issues/8#issuecomment-1426246993

**Comment by cspayne** [comment]
doi updated
