### ISSUE TITLE
Linked Data Platforms incorrect void:classPartition, void:class triples

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#20]
Per @gerontakos in https://github.com/uwlib-cams/uwlswd/issues/41#issuecomment-1694015449 \:

> the bnode in this dataset is flat-out wrong. There's no partition. "Let us be forgiving of the mistakes we make."

Seems the following triples need to be eliminated (?):

```
<https://doi.org/10.6069/uwlib.55.d.2> void:classPartition [
   void:class <https://doi.org/10.6069/uwlib.55.b.1#Platform> .
```

Related to discussion in https://github.com/uwlib-cams/uwlswd/issues/43 re: how to provide information in a dataset's triples about the class(es) of entities which are described in that dataset?

**Comment by cspayne** [comment]
@briesenberg07 
Question re:versioning - are we considering resources 'published' only once the branches they've been edited in are merged with main? 
In that case I would consider all changes to be a part of one version # update. However, if we are considering each push to be a new version, then I would need to update the version each time.

**Comment by briesenberg07** [comment]
@cspayne I agree with you when you say (slightly revised):

> considering \[a resource\] 'published' only once the \[branch it has\] been edited in are merged with main? In that case I would consider all changes \[made in the branch\] to be a part of one version # update.

To put it another way, in branch `update`, you make commits:

- add triples
- revise triples
- revise other triples

I would increment the version # for the resource ***once***, just prior to merging, as a model-***REVISION***-addition. (The revision is the biggest change, so increment the revision number.)

Tagging @gerontakos in case he has thoughts!

Does this help?

**Comment by cspayne** [comment]
@briesenberg07 
That makes sense to me! 
I'll continue to make changes but will wait to merge anything until it has been reviewed by everyone.

**Comment by gerontakos** [comment]
It looks like you want me to confirm: I confirm. Can't have a new version for every commit, that's awful. Just for each merge, and that can be considered "published," right, and the number to change is generally the revision number, the middle number, agreed. That all sounds correct.
