### ISSUE TITLE
move linked_data_platforms to directory

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#22]
- [x] Copy RDF/XML to new location
- [x] Pre-process RDF/XML
   - [x] Increment version number in RDF/XML as revision; dct:hasFormat values changing
   - [x] Remove dct:hasFormat triples
- [x] run main.py
   - [x] change $rdf2rdfa_stylesheet to xsl/rdf2htmlrdfa-plusdc.xsl \*
   - [x] check new dct:hasFormat values
   - [x] check triples in new serializations against old \*\*
   - [ ] change $rdf2rdfa_stylesheet *back to* xsl/rdf2htmlrdfa.xsl \*
- [x] Update DataCite XML
   - [x] Remove version number
   - [x] Update per https://github.com/uwlib-cams/uwlswd/issues/51 
   - [x] Update per https://github.com/uwlib-cams/uwlswd/issues/50
- [x] Update DOI at DataCite Fabrica
   - [x] Upload XML
   - [x] Update URL
- [x] Confirm DOI dereferences to new location
- [x] Delete data at old location

\* *See [Run main.py to serialize data](https://github.com/uwlib-cams/uwlswd/wiki/workflow#5-run-mainpy-to-serialize-data)*
\*\* *Only checked number of triples in the graph*

**Comment by briesenberg07** [comment]
[20230919_main.py_error.txt](https://github.com/uwlib-cams/uwlswd_vocabs/files/12666857/20230919_main.py_error.txt)

@cspayne sharing terminal error output
I suspect the use of both `/` and `\` in the filepath to directory for processing?

**Comment by briesenberg07** [comment]
Oh wait, I'm looking at the following:

```
https://uwlib-cams.github.io/gitrepos_uwlswd/uwlswd_vocabs/linked_data_platforms\linked_data_platforms.rdf does not look like a valid URI, trying to serialize this will break.
```
That seems like a URL string which combines some of the path to the target directory in my computer's file structure with a base URL portion?

**Comment by cspayne** [comment]
Looking at this now!

**Comment by cspayne** [comment]
@briesenberg07 - will you try replacing line 36 in main.py (where uri_path is set) with:

>     uri_path = "https://uwlib-cams.github.io/" + file_path_noext.replace("../", "").replace("\\", "/")

**Comment by briesenberg07** [comment]
Hmmm, stymied! I did two things:
- Per L35 comment "assumes top-level directory for file is parallel to uwlswd directory", moved directories on my computer (see \* below)
- Changed L36 [as above](https://github.com/uwlib-cams/uwlswd_vocabs/issues/22#issuecomment-1726621853)

So I'm mystified by the new error message...

[20230919_main.py_error_02.txt](https://github.com/uwlib-cams/uwlswd_vocabs/files/12667141/20230919_main.py_error_02.txt)

...where it says:

```
https://uwlib-cams.github.io/gitrepos_uwlswd/uwlswd_vocabs/linked_data_platforms\linked_data_platforms.ttl does not look like a valid URI, trying to serialize this will break.
```
I don't know where `gitrepos_uwlswd/` is coming from at this point, as that directory no longer exists on my machine...

-----
\* BMR directory structure *now/following change*
```
gitrepos/
   uwlswd/
   uwlswd_vocabs/
```

**Comment by cspayne** [comment]
@briesenberg07 Did this uri potentially end up in the rdf/xml during your first serialization attempt?

**Comment by briesenberg07** [comment]
Thanks for the above Cypress--this had indeed happened. I ran the script successfully! The expected files were output in the expected place!

But checking `dct:hasFormat` values:

**Input** (excerpt):
```
...
    <void:feature rdf:resource="http://www.w3.org/ns/formats/Turtle"/>
    <dct:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms.nt"/>
    <dct:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms.ttl"/>
    <dct:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms.jsonld"/>
    <dct:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms.html"/>
    <ldproc:containsEntity rdf:resource="https://doi.org/10.6069/uwlib.55.b.1#Platform"/>
...
```

**Output** (excerpt):
```
...
    <void:feature rdf:resource="http://www.w3.org/ns/formats/Turtle"/>
    <dcterms:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms.nt"/>
    <dcterms:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms.ttl"/>
    <dcterms:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms.jsonld"/>
    <dcterms:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms.html"/>
    <dcterms:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms/linked_data_platforms.ttl"/>
    <dcterms:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms/linked_data_platforms.nt"/>
    <dcterms:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms/linked_data_platforms.jsonld"/>
    <dcterms:hasFormat rdf:resource="https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms/linked_data_platforms.html"/>
    <ldproc:containsEntity rdf:resource="https://doi.org/10.6069/uwlib.55.b.1#Platform"/>
...
```

**Comment by cspayne** [comment]
Yay!

The repeat dct:hasFormat output is because of the location change - if you remove or update the dct:hasFormat triples before serialization, then the script will add the correct ones.

It is not set to remove any dct:hasFormat triples that are already in the rdf/xml so that in circumstances where a resource _does_ have additional formats, those are not lost. 
This does mean that when the uri is changing, there is the additional step of removing the old dct:hasFormat triples.

**Comment by briesenberg07** [comment]
@cspayne did your DOI URL update take effect yet? I checked this vocab this morning and DOI dereferenced to new URL (after making DataCite Fabrica updates on Tuesday). So, it takes... something less than 2 days to take effect?

**Comment by cspayne** [comment]
> @cspayne did your DOI URL update take effect yet? I checked this vocab this morning and DOI dereferenced to new URL (after making DataCite Fabrica updates on Tuesday). So, it takes... something less than 2 days to take effect?

Yes! I had to clear the cache in my browser and since then it's been pretty instantaneous.
