### ISSUE TITLE
children's lit categories incorrect triple

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd_vocabs#27]
children's lit categories uses `dct:alternate` for an alternate title - the correct property is [dct:alternative](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#alternative)

**Comment by gerontakos** [comment]
Note: at some later date, we really need to incorporate validation into the workflow. If we're writing RDF/XML manually, mistakes like this will always happen. Once we settle on a structure for the RDF/XML, I can write an XML schema to validate. I'll create an issue for this in, uh, uwlswd! I expect that's where validation tools would be stored?

**Comment by cspayne** [comment]
This was fixed previously - the alternate title now uses dcterms:alternative
