### ISSUE TITLE
simple mistakes

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs#9]
# SPARQLing vocabs...
## rdf:Properties
```
SELECT DISTINCT ?p WHERE 
{ ?class rdf:type rdf:Property ;
        ?p ?o .}
```
![image](https://user-images.githubusercontent.com/27664966/216191596-8afc5160-a52d-4b6f-a108-1ef0e44c2e5a.png)
## skos:Concepts
![image](https://user-images.githubusercontent.com/27664966/216192315-69385c37-9f51-46ae-a58e-52811e06639f.png)

**Comment by cspayne** [comment]
@briesenberg07 
I created a branch in uwlswd_vocabs to work on its cleanup issues.

**Comment by briesenberg07** [comment]
Thanks for the heads up @cspayne !
